name: Skopeo UBI-IB vars.collector
run-name: ${{ github.actor }} is Collecting ğŸš€
on: [push]
jobs:
  Skopeo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Main Skopeo Script
        run: |
          ls -lah ${{ github.workspace }}
          DATE=`date '+%Y%m%d-%H%M'`
          # install deps
          apt-get update && apt-get install -y skopeo
          skopeo login registry1.dso.mil -u ${{ vars.REGISTRY_USER }} -p ${{ secrets.REGISTRY_TOKEN }}
          skopeo sync \
              --src-creds=${{ vars.REGISTRY_USER }}:${{ secrets.REGISTRY_TOKEN }} \
              --src yaml --dest dir ${{ vars.COLLECTOR }}.yml ${{ vars.COLLECTOR }}
          tar -cvzf ${{ vars.COLLECTOR }}-$DATE.tgz ${{ vars.COLLECTOR }}
          ls -alh ${{ vars.COLLECTOR }}-$DATE.tgz

      - run: echo "ğŸ This job's status is ${{ job.status }}."
  Code:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: 'Bundle Repo1 code base for ${{ vars.COLLECTOR }}'
        run: |
            DATE=`date '+%Y%m%d-%H%M'`
            git submodule update --init --recursive
            git bundle create --progress ${{ vars.COLLECTOR }}_$DATE.bundle --all
            ls -alht *